### ISSUE TITLE
No module named 'pysvg'

### ISSUE THREAD

**Issue by babllz** [patorf/PhotoScan_Analysis#1]
Hi!
I know Photoscan uses Python 3.3 as scripting engine (or more recent), but despite I successfully installed the `pysvg-py3` module through the terminal (https://github.com/alorence/pysvg-py3), Photoscan can't run your script:
```
Traceback (most recent call last):
File "/Applications/Photoscan Pro/Plugins/PhotoScan_Analysis-master/analysis.py", line 19, in <module>
from pysvg.builders import *
ImportError: No module named 'pysvg'
```
I'm sure I'd find it very useful, hope to figure out a solution and try it w/ my models!

**Comment by patorf** [comment]
Hi, 
I think you can not install `pysvg` because `photoscan` comes with its own python interpreter, which do not allow this. 
What I have done is to download the source files of `pysvg` and store it in a folder inside your `PhotoScan_Analysis-master` folder. e.g. the core.py file is stored in ` PhotoScan_Analysis-master\pysvg\core.py`

**Comment by babllz** [comment]
Thank you @patorf!
It worked well in reading the `pysvg`, but another error appeared as I launched the script:

```
Traceback (most recent call last):

File "/Applications/Photoscan Pro/Plugins/PhotoScan_Analysis-master/analysis.py", line 1659, in <module>
project.create_project_SVG(svg_filename, svg_factor, svg_cols)

File "/Applications/Photoscan Pro/Plugins/PhotoScan_Analysis-master/analysis.py", line 533, in create_project_SVG
s = svg()
NameError: name 'svg' is not defined
```

--I'm sorry for bothering you, I know Python just a little and couldn't solve this issue by myself.

**Comment by patorf** [comment]
try the original  `pysvg`  from http://codeboje.de/pysvg-021/ 
in the pysvg-py3 version the class name svg begin with a capitalized 'S'

**Comment by babllz** [comment]
Done: it returns the same error :/

**Comment by patorf** [comment]
sorry, but I can not reproduce your error.

**Comment by babllz** [comment]
Thanks anyway!
